---
title: Mindset Dojo

google_analytics_id: G-7PD1BFF7RG

collections:
  authors:
    output: true
    permalink: /authors/:name/
  insights:
    output: true
    permalink: /insights/:slug/
  forms:
    output: true
    permalink: /forms/:slug/

defaults:
  - scope:
      path: ""
      type: insights
    values:
      article: true
  - scope:
      path: ""
      type: forms
    values:
      article: true

action_links:
  authors: /authors/
  program: /program/
  connect: https://connect.mindset.dojo.center

header_links:
  - label: MISSION
    href: /
  - label: PROGRAM
    href: /program/
  - label: FORMS
    href: /forms/
  - label: AUTHORS
    href: /authors/

footer_primary_links:
  - label: MISSION
    href: /
  - label: PROGRAM
    href: /program/
  - label: FORMS
    href: /forms/
  - label: AUTHORS
    href: /authors/
  - label: SUPPORT
    href: /support/

footer_secondary_links:
  - label: Privacy Policy
    href: /privacy/
  - label: Open Source License
    href: /license/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
...
