---
title: Mindset Dojo

google_analytics_id: G-7PD1BFF7RG

collections: {}

defaults: []

action_links:
  connect: /connect/
  welcome: /welcome/

header_links:
  - label: HOME
    href: /
  - label: WELCOME
    href: /welcome/
  - label: CONNECT
    href: /connect/

footer_primary_links:
  - label: HOME
    href: /
  - label: WELCOME
    href: /welcome/
  - label: CONNECT
    href: /connect/

footer_secondary_links:
  - label: Privacy Policy
    href: /privacy/
  - label: Open Source License
    href: /license/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
...
