name: Deploy Site

on:
  # Allow dev builds anytime
  workflow_dispatch: null

  # Auto-deploy only after both gates pass and PR is merged to main
  workflow_run:
    workflows: ["Super-Linter", "HTMLProofer"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write  # required for GitHub Pages deployment

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: ðŸ“ Generate _config.production.yml
        run: |
            if [[ "${GITHUB_REPOSITORY}" == "mindset-dojo/mindset-dojo.github.io" ]]; then
              URL="https://mindset.dojo.center"
              BASEURL=""
            else
              URL="https://${GITHUB_REPOSITORY_OWNER}.github.io"
              BASEURL="/${GITHUB_REPOSITORY#*/}"
            fi

            cat > _config.production.yml <<EOF
        
            # Auto-generated by GitHub Actions
            url: "${URL}"
            baseurl: "${BASEURL}"
            EOF


      - name: Build Jekyll site
        run: bundle exec jekyll build --config _config.yml,_config.production.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
